### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by FMDSF** [mandre/kano-i18n-sync#1]
Hi there,

new syntax to pull translations initiated, finally. I typed in: **./pull_translations.py --lang de**

> [fmdsf@localhost kano-i18n-sync]$ ./pull_translations.py --lang de

>Traceback (most recent call last):
  File "./pull_translations.py", line 135, in <module>
    ssh.connect('kano')
  File "/usr/local/lib/python3.7/site-packages/paramiko/client.py", line 446, in connect
    passphrase,
  File "/usr/local/lib/python3.7/site-packages/paramiko/client.py", line 764, in _auth
    raise saved_exception
  File "/usr/local/lib/python3.7/site-packages/paramiko/client.py", line 740, in _auth
    self._transport.auth_publickey(username, key)
  File "/usr/local/lib/python3.7/site-packages/paramiko/transport.py", line 1580, in auth_publickey
    return self.auth_handler.wait_for_response(my_event)
  File "/usr/local/lib/python3.7/site-packages/paramiko/auth_handler.py", line 250, in wait_for_response
    raise e
**paramiko.ssh_exception.AuthenticationException: Authentication failed.**

Where is the paramiko failing? On the KANO Host or on my Fedora system which is initiating the script?

Fernando

**Comment by mandre** [comment]
Hi @FMDSF, thanks for the report. There was an issue where the scripts didn't read the SSH config from the ssh config file, so it would fail if you used different usernames on the machine you connected from and on the kano host. This should now be fixed with 8ec82bd. Let me know if it solves it for you.

**Comment by FMDSF** [comment]
Hi mandre, 

thank you so much for your help!

I cloned the files and it looks like it is starting to synchronize the files, now. :) However it is now stopping at a different point when trying to fetch the version of kano-apps.

Is this another issue or just missing knowledge how to use your script, properly?

Here is what is happening on my machine. 
```
[fmdsf@localhost kano-i18n-sync]$ ./pull_translations.py --lang de

Copying sudoers files



Syncing translations for kano-apps

Fetching package version for kano-apps

Could not fetch version for kano-apps

```

**Comment by mandre** [comment]
Try running the script again and see if it works this time. It's probably because it needed to start a new session for the new sudoers file to be used.

**Comment by mandre** [comment]
Also, could you open a new issue for this? Thanks!

**Comment by FMDSF** [comment]
OK. I will test again. If the issue still persist I'll open a new one. I will update you.
Thx to you!
